# Generated by Django 4.2.28 on 2026-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AddField(
            model_name='application',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Javob berildi'),
        ),
        migrations.AddField(
            model_name='application',
            name='reply_text',
            field=models.TextField(blank=True, null=True, verbose_name='Admin javobi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('news', 'Yangilik yuborish'), ('ads', 'Reklama joylashtirish'), ('report', 'Shikoyat qilish'), ('collab', 'Hamkorlik'), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(verbose_name='Xabar matni'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.BigIntegerField(verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username'),
        ),
    ]
