# Generated by Django 4.2.29 on 2026-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_application_options_application_is_answered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['is_closed', '-updated_at'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AddField(
            model_name='application',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Yopilgan (Steam Style)'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgarish"),
        ),
    ]
