# Generated by Django 4.2.29 on 2026-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_application_options_application_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subject',
            field=models.CharField(default="Mavzu ko'rsatilmagan", max_length=50, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Yopilgan'),
        ),
    ]
