# Generated by Django 4.2.29 on 2026-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_application_subject_alter_application_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='reply_text',
        ),
        migrations.RemoveField(
            model_name='application',
            name='text',
        ),
        migrations.AddField(
            model_name='application',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Chat tarixi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subject',
            field=models.CharField(default="Mavzu ko'rsatilmadi", max_length=50, verbose_name='Mavzu'),
        ),
    ]
